Authentication
vipulchakravarthy/App_Development pull request #2
Opened 2020-03-27 13:10 UTC by vipulchakravarthy

I have completed task-1 & 2. Pls, review it.

2020-03-27 16:01 UTC, praveengarimella commented on project1/application.py
>      data = User.query.all()
desc order?

2020-03-27 16:11 UTC, vipulchakravarthy commented on project1/application.py
>      data = User.query.all()
Okay, I'll update the query.

2020-03-28 05:46 UTC, praveengarimella requested changes
I don't want to repeat the same comments again. Please remove the bin files from the repo and then I'll review the code.

2020-03-28 06:22 UTC, vipulchakravarthy commented
Sorry, It took some time for me to figure out the issue with .gitignore. I pushed all the binary files into .gitignore.

2020-03-28 06:22 UTC, vipulchakravarthy commented on project1/application.py
>      data = User.query.all()
I have updated the query.

2020-03-28 06:24 UTC, vipulchakravarthy commented
Can I merge this branch?

2020-04-03 11:48 UTC, praveengarimella commented
Does this still need a review? If not please close it.

2020-04-03 17:20 UTC, merged